### ISSUE TITLE
Remove upper version bounds

### ISSUE THREAD

**Issue by curry684** [jasoncorbett/more-black#1]
Thanks for the great theme, loving it on my OLED laptop screen   👍 

However it just stopped working last week, reverting my IDE to the standard washed out gray Darcula. Turns out the More Black theme is, out of 20 themes installed, the only one declaring incompatibility with 2023.3 that was released last week.

So uhm, this is really annoying to lose theme because of keeping the IDE up to date automatically. Please remove the upper version bounds so it doesn't break every few months unannounced.

**Comment by jasoncorbett** [comment]
Wow, I wish that's how it worked!  Unfortunately the only place I can find to put in the version is in the [theme xml](https://github.com/jasoncorbett/more-black/blob/main/src/main/resources/More_Black.xml) and in the [new theme xml](https://github.com/jasoncorbett/more-black/blob/main/src/main/resources/expUI_More_Black.xml), in the ideVersion tag.  If you know of another way to make it compatible with future updates let me know.

Unfortunately the way it usually works, is I see that they released a new version and it's not working and I update it.  I think other plugin builders are just better at watching for the EAPs and updating then.  I'll try to get better.

I've submitted the new version, should only take a day to get approved, sorry for being late.

**Comment by jasoncorbett** [comment]
I did find this, looking at how to make it work:
https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#build-number-format

**Comment by jasoncorbett** [comment]
I think I've got it, thanks for the bug!

Version 10 (which will hopefully come out tomorrow) should have it fixed.
![Screenshot 2023-12-11 at 11 30 20 AM](https://github.com/jasoncorbett/more-black/assets/2044372/aef23041-f687-4f18-bd30-0fce39d05039)

**Comment by curry684** [comment]
Cheers and no worries, thanks for the great theme - tried about 20 "black" ones in total and yours is the best   😆
